### ISSUE TITLE
Current NPM release does not reflect current code

### ISSUE THREAD

**Issue by LOZORD** [tillarnold/fixed-2d-array#10]
If this project isn't dead, there is a nasty bug with the constructor where the two dimension args are flipped (from `node_modules/fixed-2d-array/lib/fixed-2d-array.js`):

``` js
var Fixed2DArray = function Fixed2DArray(width, height, defaultValue) {
  this._width = width;
  this._height = height;
  this._grid = [];
  for (var i = 0; i < width; i++) {
    this._grid[i] = [];
    for (var j = 0; j < height; j++) {
      this._grid[i][j] = defaultValue;
    }
  }
};
```

**Comment by possibly** [comment]
This is just like issue #7 ! I think if we just update the npm package [via the instructions here](https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package), we should be good to go.

What do you think, @tillarnold ?

**Comment by tillarnold** [comment]
Oh yeah sure we should publish a new version.  We might want to publish it as version 2.0 because this is a breaking change, right? I'm currently on my way to work but I can publish the release when I come home.

**Comment by tillarnold** [comment]
I published the release.

**Comment by possibly** [comment]
> We might want to publish it as version 2.0 because this is a breaking change, right? 

Thats what I would have done. Thanks!
